### ISSUE TITLE
Compatible with daily limit of exposure detections calls?

### ISSUE THREAD

**Issue by LukasMasuch** [CovidShield/server#18]
With the most recent update of the exposure notification API, Apple and Google added a new limit for how many key data files can be checked for exposure matches. The daily limit is [15 for iOS](https://developer.apple.com/documentation/exposurenotification/enmanager/3586331-detectexposures) and [20 for Android](https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf). The current version of the CovidShield server uses a period of 2 hours to create key data files. So, one day has 12 key data files which is within the current limits. However, if the user also has to download key data files from previous days, there might be more files per day than the allowed limit. This might get even more complicated if there are multiple regional key data files per time period. Is there already something build-in or planned for the CovidShield server to keep the number of daily key data files (required for exposure matching) within the new limits?

**Comment by burke** [comment]
We've changed the batch size to 6 hours now. We had a chat with Google yesterday where I think we all kind of agreed that the zipfiles should allow inclusion of multiple regions per zipfile, so I hope that change gets made to the protocol.

**Comment by LukasMasuch** [comment]
Thanks for the clarification! We got the same suggestion to use a larger time interval (6, 12, 24h). Initial support for multiple regions for the export already got added to the  reference server, so I assume that the protocol will be adapted soon as well: https://github.com/google/exposure-notifications-server/commit/4e5e8f71aef4fd3645732a52448c3a6c2f45b9d9
